[profile.release]
lto = true

[workspace]
members = [
    "logic",
    "env-runners/native", "env-runners/browser", "env-runners/lambda", "env-runners/lambda-cache",
    "lang-runners/python"
]
# https://github.com/wasmerio/wasmer/issues/3377
resolver = "2"
