(* type id = string *)
(* type coords = int * int *)
(* type team = string *)
(* type basic_obj = {id: id; coords: coords} *)
(* type terrain_type = Wall *)
(* type terrain = {type_: terrain_type} *)
(* type unit_type = Soldier *)
(* type unit_ = {type_: unit_type; team: team; health: int} *)
(* type obj_details = Terrain of terrain | Unit of unit_ *)

(* module Obj = struct *)
(*   type t = basic_obj * obj_details *)

(*   let wrap obj = *)
(*     match obj with *)
(*     | Terrain {id; coords; type_} -> ({id; coords}, {type_}) *)
(*     | Unit {id; coords; team; health} -> ({id; coords}, {team; health}) *)
(* end *)
