[package]
name = "logic"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>", "Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

[features]
robot-runner-not-send = []

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_with = { version = "1.4.0", default-features = false }
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
multimap = "0.8.1"
strum = { version = "0.18.0", features = ["derive"] }
thiserror = "1.0.20"
futures-util = "0.3.5"
async-trait = "0.1.36"

schemars = { version = "0.8.0-alpha-4", optional = true }

[[bin]]
name = "gen_schema"
path = "src/gen_schema.rs"
required-features = ["schemars"]
