[package]
name = "logic"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>", "Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

[features]
robot-runner-not-send = []

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_with = { version = "1.4.0", default-features = false }
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
multimap = "0.8.1"
strum = { version = "0.18.0", features = ["derive"] }
thiserror = "1.0.20"
itertools = "0.9.0"
maplit = "1.0.2"
futures-util = "0.3.5"
async-trait = "0.1.36"
