[package]
name = "lambda"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logic = { path = "../../logic" }
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master" }
rusoto_core = "0.43.0"
rusoto_sqs = "0.43.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.2.18"
