[package]
name = "lambda"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>", "Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.2.1"
rusoto_core = "0.43.0"
rusoto_sqs = "0.43.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
